import pygame

#Constants for game
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FPS = 60

#PLAYERS KEYS
P1_KEYS = {'left': pygame.K_a, 'right': pygame.K_d, 'up': pygame.K_w, 'down': pygame.K_s}
P2_KEYS ={'left': pygame.K_LEFT, 'right': pygame.K_RIGHT, 'up': pygame.K_UP, 'down': pygame.K_DOWN}

#COLORS
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
GOLD = (255, 215, 0)
GRAY = (50, 50, 50)
GREEN = (0, 255, 0)
LIGHT_GRAY = (200, 200, 200)
RED = (255, 0, 0)
WHITE = (255, 255, 255)



#MENU SCREENS
MENU = "menu"
PRACTICE = "practice"
LOCAL_MENU = "local_menu"
LOCAL = "local"
MULTIPLAYER = "multiplayer"
SETTINGS = "settings"

#SETTINGS LOGO
SETTINGS_ICON_SIZE = 40
SETTTNGS_ICON_MARGIN = 20

#SCOREBOARD
SCOREBOARD_FONT_SIZE = 32
SCOREBOARD_PADDING = 10
SCOREBOARD_BORDER_THICKNESS = 1
SCOREBOARD_OFFSET_X = 60
SCOREBOARD_OFFSET_Y = 20

#TIMER SETTINGS
TIMER_DURATION_SECONDS = 180
TIMER_GAP_Y = 24

#Rink Settings
RINK_WIDTH = 0.50
RINK_HEIGHT = 0.85 
RINK_PADDING_X = 0.1
RINK_PADDING_Y = .08
RINK_BORDER_THICKNESS = 3
RINK_LINE_THICKNESS = 2
RINK_CIRCLE_RADIOUS = 0.1
GOAL_WIDTH = 0.15
GOAL_HEIGHT = .06 

#GOAL Settings
GOAL_BORDER_THICKNESS = 1
GOAL_FLASH_COLOR = GOLD
GOAL_FLASH_DURATION = 90
GOAL_FLASH_ALPHA = 80

#PUCK SETTINGS
PUCK_RADIUS = 12
PUCK_SPEED = 4
PUCK_MAX_SPEED = 25
PUCK_FRICTION = .996
PUCK_MIN_SPEED = .7

#PADDLE SETTINGS
PADDLE_RADIUS = 20
PADDLE_SPEED = 5
PADDLE_DASH_SPEED = 12
PADDLE_DASH_DURATION = 150
PADDLE_DASH_WINDOW = 250

#CPU PADDLE SETTNGS
CPU_PADDLE_SPEED = 5
CPU_AIM_RANGE = 100
CPU_REACTION_DELAY_FRAMES = 12
CPU_TRACKING_DEADZONE = 15
CPU_PREDICTION_FRAMES = 8
CPU_URGENCY_RANGE = 250
CPU_MAX_URGENCY_SPEED = 9

#PAUSE SETTINGS
PAUSE_OVERLAY_ALPHA = 150
PAUSE_MENU_BUTTON_WIDTH = 160
PAUSE_MENU_BUTTON_HEIGHT = 45
PAUSE_FONT_SIZE = 80
