import pygame

#Constants for game
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FPS = 60

#PLAYERS KEYS
P1_KEYS = {'left': pygame.K_a, 'right': pygame.K_d, 'up': pygame.K_w, 'down': pygame.K_s}
P2_KEYS ={'left': pygame.K_LEFT, 'right': pygame.K_RIGHT, 'up': pygame.K_UP, 'down': pygame.K_DOWN}

#COLORS
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
GOLD = (255, 215, 0)
GRAY = (50, 50, 50)
GREEN = (0, 255, 0)
LIGHT_GRAY = (200, 200, 200)
RED = (255, 0, 0)
WHITE = (255, 255, 255)

MENU_BUTTON_X = .08
MENU_BUTTON_WIDTH = .28
MENU_BUTTON_HEIGHT = 0.09
MENU_FIRST_BUTTON_Y = 0.35
MENU_BUTTON_GAP = 0.03

MENU_ARTWORK_X = 0.43
MENU_ARTWORK_Y = 0.24
MENU_ARTWORK_WIDTH = 0.50
MENU_ARTWORK_HEIGHT = 0.62

MENU_TITLE_X = 0.08
MENU_TITLE_Y = 0.08
MENU_TITLE_FONT_SCALE = 0.11

MENU_LABEL_X = 0.08
MENU_LABEL_Y = 0.27
MENU_LABEL_FONT_SCALE = 0.045

# Pixel measurements
MENU_ARTWORK_BORDER_RADIUS = 15
MENU_ARTWORK_BORDER_WIDTH = 2

MENU_BACKGROUND_COLOR = (7, 15, 28)
MENU_RINK_LINE_COLOR = (35, 65, 90)

# MAIN MENU RINK
MENU_RINK_MARGIN_X = 0.025
MENU_RINK_MARGIN_Y = 0.04

MENU_RINK_BORDER_WIDTH = 3
MENU_RINK_BORDER_RADIUS = 20

MENU_GOAL_Y = 0.38
MENU_GOAL_WIDTH = 0.025
MENU_GOAL_HEIGHT = 0.24
MENU_GOAL_BORDER_WIDTH = 3


#MENU SCREENS
MENU = "menu"
PRACTICE = "practice"
LOCAL_MENU = "local_menu"
LOCAL = "local"
MULTIPLAYER = "multiplayer"
SETTINGS = "settings"

#SETTINGS SCREEN
SETTINGS_TITLE_FONT_SIZE = 72
SETTINGS_PANEL_WIDTH = 700
SETTINGS_PANEL_HEIGHT = 400
SETTINGS_PANEL_PADDING = 25
SETTINGS_BACK_BUTTON_WIDTH = 180
SETTINGS_BACK_BUTTON_HEIGHT = 50
SETTINGS_BACK_BUTTON_MARGIN = 30
SETTINGS_SCROLL_SPEED = 30
SETTINGS_LABEL_FONT_SIZE = 36
SETTINGS_OPTION_BUTTON_WIDTH = 120
SETTINGS_OPTION_BUTTON_HEIGHT = 45
SETTINGS_OPTION_GAP = 20

#SETTINGS ROW POSITIONS
SETTINGS_DIFFICULTY_ROW_Y = 70
SETTINGS_WIN_CONDITION_ROW_Y = 180
SETTINGS_MATCH_LENGTH_ROW_Y = 290
SETTINGS_LABEL_GAP = 10
SETTINGS_ARROW_BUTTON_SIZE = 45
SETTINGS_MINUTE_TEXT_WIDTH = 140

#SETTINGS LOGO
SETTINGS_ICON_SIZE = 40
SETTINGS_ICON_MARGIN = 20

#SCOREBOARD
SCOREBOARD_FONT_SIZE = 32
SCOREBOARD_PADDING = 10
SCOREBOARD_BORDER_THICKNESS = 1
SCOREBOARD_OFFSET_X = 60
SCOREBOARD_OFFSET_Y = 20

#TIMER SETTINGS
TIMER_DURATION_SECONDS = 180
TIMER_GAP_Y = 24

#Rink Settings
RINK_WIDTH = 0.50
RINK_HEIGHT = 0.85 
RINK_PADDING_X = 0.1
RINK_PADDING_Y = .08
RINK_BORDER_THICKNESS = 3
RINK_LINE_THICKNESS = 2
RINK_CIRCLE_RADIOUS = 0.1
GOAL_WIDTH = 0.15
GOAL_HEIGHT = .06 

#GOAL Settings
GOAL_BORDER_THICKNESS = 1
GOAL_FLASH_COLOR = GOLD
GOAL_FLASH_DURATION = 90
GOAL_FLASH_ALPHA = 80

#PUCK SETTINGS
PUCK_RADIUS = 26
PUCK_SPEED = 4
PUCK_MAX_SPEED = 20
PUCK_FRICTION = .996
PUCK_MIN_SPEED = .7

#PADDLE SETTINGS
PADDLE_RADIUS = 26
PADDLE_SPEED = 5
PADDLE_DASH_SPEED = 12
PADDLE_DASH_DURATION = 150
PADDLE_DASH_WINDOW = 250

#CPU PADDLE SETTNGS
CPU_PADDLE_SPEED = 5
CPU_AIM_RANGE = 100
CPU_REACTION_DELAY_FRAMES = 12
CPU_TRACKING_DEADZONE = 15
CPU_PREDICTION_FRAMES = 8
CPU_URGENCY_RANGE = 250
CPU_MAX_URGENCY_SPEED = 9

#PAUSE SETTINGS
PAUSE_OVERLAY_ALPHA = 150
PAUSE_MENU_BUTTON_WIDTH = 160
PAUSE_MENU_BUTTON_HEIGHT = 45
PAUSE_FONT_SIZE = 80
